"""
P6 — Morning Brief Generator
Orchestrates: Watchlist scan → Screenshot → RAG → Claude → Telegram
"""
import logging
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Optional
from zoneinfo import ZoneInfo

import config
from mcp_client import get_mcp_client
from watchlist import get_watchlist
from analysis import scan_symbols, ScanResult
from rag import query_knowledge, generate_trading_advice
from notifier import send_telegram_message, send_telegram_photo

logger = logging.getLogger(__name__)

ICT = ZoneInfo("Asia/Ho_Chi_Minh")

# Store latest brief in memory
_latest_brief: Optional[dict] = None


def _format_brief_text(
    scan_results: list[ScanResult],
    ai_analysis: str,
    timestamp: datetime,
) -> str:
    """Format morning brief as Telegram-friendly text."""
    now_str = timestamp.strftime("%d/%m/%Y %H:%M ICT")
    n = len(scan_results)

    lines = [
        f"🌅 *MORNING BRIEF — {now_str}*",
        f"📊 Watchlist scan: *{n} symbols*",
        "",
    ]

    # Per-symbol table
    lines.append("*Symbol  │ Price     │ TT   │ Vol%  │ VCP*")
    lines.append("─" * 45)

    for r in scan_results:
        if r.error:
            lines.append(f"❌ {r.symbol:8} — Error: {r.error[:30]}")
            continue

        vcp_flag = "⭐VCP" if r.vcp.detected else "    "
        change = f"+{r.change_pct:.1f}%" if r.change_pct >= 0 else f"{r.change_pct:.1f}%"
        vol_pct = f"{r.vcp.volume_ratio*100:.0f}%"

        lines.append(
            f"`{r.symbol:8}` │ {r.price:>10,.2f} │ {r.trend_template.score}/8 │ {vol_pct:>5} │ {vcp_flag}"
        )

    lines.append("")

    # VCP highlights
    vcps = [r for r in scan_results if r.vcp.detected and not r.error]
    if vcps:
        lines.append("🎯 *VCP Setups đáng chú ý:*")
        for r in vcps:
            lines.append(f"• *{r.symbol}*: {r.vcp.note}")
            if r.vcp.pivot_level:
                lines.append(f"  → Pivot breakout: `{r.vcp.pivot_level:,.2f}`")
        lines.append("")

    # AI analysis
    lines.append("🧠 *Minervini AI Assessment:*")
    lines.append(ai_analysis)
    lines.append("")
    lines.append("─" * 45)
    lines.append(f"_Generated by TradingViewProject v6.0_")

    return "\n".join(lines)


async def generate_morning_brief() -> Optional[dict]:
    """
    Full morning brief orchestration:
    1. Get watchlist
    2. MCP scan (quote + study values)
    3. Screenshot top VCP candidate
    4. RAG + Claude analysis
    5. Send Telegram (text + photo)
    6. Return brief dict
    """
    global _latest_brief
    mcp = get_mcp_client()
    timestamp = datetime.now(ICT)

    logger.info(f"[Brief] Starting morning brief at {timestamp.isoformat()}")

    # 1. Get watchlist
    symbols = get_watchlist()
    if not symbols:
        logger.warning("[Brief] Watchlist is empty — skipping brief")
        return None

    # 2. MCP health check
    health = await mcp.health_check()
    if not health.get("connected") and config.MCP_ENABLED:
        logger.warning("[Brief] TradingView MCP not connected — brief may have limited data")

    # 3. Scan symbols
    logger.info(f"[Brief] Scanning {len(symbols)} symbols: {symbols}")
    try:
        scan_results = await scan_symbols(symbols, mcp)
    except Exception as e:
        logger.error(f"[Brief] Scan failed: {e}")
        scan_results = []

    # 4. Screenshot top VCP (or top TT score)
    screenshot_path: Optional[Path] = None
    top_candidates = [r for r in scan_results if r.vcp.detected and not r.error]
    if not top_candidates:
        top_candidates = [r for r in scan_results if not r.error]

    if top_candidates and config.MCP_ENABLED and health.get("connected"):
        top = top_candidates[0]
        logger.info(f"[Brief] Capturing screenshot for {top.symbol}")
        try:
            screenshot_path = await mcp.capture_screenshot(
                symbol=top.symbol,
                timeframe="D",
                region="chart",
                save_path=Path(__file__).parent / "screenshots" / f"brief_{top.symbol}_{timestamp.strftime('%Y%m%d')}.png"
            )
        except Exception as e:
            logger.warning(f"[Brief] Screenshot failed: {e}")

    # 5. RAG + Claude analysis
    ai_analysis = ""
    if config.RAG_ENABLED and config.ANTHROPIC_API_KEY:
        try:
            # Build context from top results
            vcp_symbols = [r.symbol for r in scan_results if r.vcp.detected and not r.error]
            top_tt = sorted([r for r in scan_results if not r.error],
                           key=lambda x: x.trend_template.score, reverse=True)[:3]

            query = f"Morning brief scan: VCP setups {vcp_symbols}, " \
                    f"top Trend Template scores {[f'{r.symbol}:{r.trend_template.score}/8' for r in top_tt]}, " \
                    f"Stage 2 analysis market overview"

            chunks = query_knowledge(query, n_results=config.RAG_TOP_K)

            # Build signal dict for generate_trading_advice
            signal_data = {
                "type": "morning_brief",
                "symbols_scanned": len(symbols),
                "vcp_detected": vcp_symbols,
                "top_tt_scores": [f"{r.symbol}: {r.trend_template.score}/8" for r in top_tt],
                "timestamp": timestamp.isoformat(),
            }

            ai_analysis = await asyncio.to_thread(
                generate_trading_advice,
                signal=signal_data,
                chunks=chunks,
                context_type="morning_brief"
            )
        except Exception as e:
            logger.warning(f"[Brief] AI analysis failed: {e}")
            ai_analysis = "_AI analysis unavailable_"
    else:
        ai_analysis = "_RAG/Claude not configured — enable ANTHROPIC_API_KEY and RAG_ENABLED_"

    # 6. Format brief
    brief_text = _format_brief_text(scan_results, ai_analysis, timestamp)

    # 7. Send Telegram
    try:
        if screenshot_path and screenshot_path.exists():
            await asyncio.to_thread(send_telegram_photo, screenshot_path, caption=brief_text[:1024])
            # Send full text if caption truncated
            if len(brief_text) > 1024:
                await asyncio.to_thread(send_telegram_message, brief_text)
        else:
            await asyncio.to_thread(send_telegram_message, brief_text)
        logger.info("[Brief] Morning brief sent to Telegram ✅")
    except Exception as e:
        logger.error(f"[Brief] Telegram send failed: {e}")

    # 8. Cache
    brief = {
        "timestamp": timestamp.isoformat(),
        "symbols_scanned": len(symbols),
        "scan_results": [
            {
                "symbol": r.symbol,
                "price": r.price,
                "change_pct": r.change_pct,
                "trend_template_score": r.trend_template.score,
                "trend_template_stage": r.trend_template.stage,
                "vcp_detected": r.vcp.detected,
                "volume_ratio": r.vcp.volume_ratio,
                "pivot_level": r.vcp.pivot_level,
                "note": r.vcp.note,
                "error": r.error,
            }
            for r in scan_results
        ],
        "ai_analysis": ai_analysis,
        "screenshot": str(screenshot_path) if screenshot_path else None,
        "text": brief_text,
    }
    _latest_brief = brief
    return brief


def get_latest_brief() -> Optional[dict]:
    """Return the most recent morning brief."""
    return _latest_brief
