"""
Security Report Generator — Outputs findings as Markdown and JSON.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from security import SecurityReport, Severity


SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
    Severity.INFO: "ℹ️",
}


def to_markdown(report: SecurityReport) -> str:
    """Generate a Markdown security report."""
    lines = []
    lines.append("# 🛡️ Mini-MDASH Security Report")
    lines.append("")
    lines.append(f"**Target**: `{report.target}`")
    lines.append(f"**Timestamp**: {report.timestamp}")
    lines.append(f"**Files Scanned**: {report.total_files_scanned}")
    lines.append("")

    # Summary box
    s = report.summary
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| 🔴 Critical | **{s.get('critical', 0)}** |")
    lines.append(f"| 🟠 High | **{s.get('high', 0)}** |")
    lines.append(f"| 🟡 Medium | **{s.get('medium', 0)}** |")
    lines.append(f"| 🟢 Low | **{s.get('low', 0)}** |")
    lines.append(f"| ℹ️ Info | **{s.get('info', 0)}** |")
    lines.append(f"| **Total** | **{s.get('total_findings', 0)}** |")
    lines.append("")
    lines.append(f"**Scanners**: {', '.join(s.get('scanners_used', []))}")
    lines.append("")

    # Verdict
    if s.get("critical", 0) > 0:
        lines.append("> **VERDICT: 🔴 CRITICAL — Immediate action required**")
    elif s.get("high", 0) > 0:
        lines.append("> **VERDICT: 🟠 HIGH — Address before production deployment**")
    elif s.get("medium", 0) > 0:
        lines.append("> **VERDICT: 🟡 MEDIUM — Review and remediate**")
    else:
        lines.append("> **VERDICT: ✅ CLEAN — No significant issues found**")
    lines.append("")

    # Findings detail
    if report.findings:
        lines.append("## Findings")
        lines.append("")

        current_severity = None
        for f in report.findings:
            if f.severity != current_severity:
                current_severity = f.severity
                emoji = SEVERITY_EMOJI.get(f.severity, "❓")
                lines.append(f"### {emoji} {f.severity.value.upper()}")
                lines.append("")

            lines.append(f"#### [{f.rule_id}] {f.title}")
            lines.append(f"- **File**: `{_short_path(f.file)}` (line {f.line})")
            lines.append(f"- **Confidence**: {f.confidence:.0%}")
            if f.cwe:
                lines.append(f"- **CWE**: [{f.cwe}](https://cwe.mitre.org/data/definitions/{f.cwe.split('-')[1]}.html)")
            lines.append(f"- **Description**: {f.description}")
            if f.evidence:
                lines.append(f"- **Evidence**: `{f.evidence[:100]}`")
            if f.remediation:
                lines.append(f"- **Fix**: {f.remediation}")
            lines.append("")

    # Probe results (for Level B/C)
    if report.probe_results:
        lines.append("## Exploit Simulation Results")
        lines.append("")
        lines.append("| Probe | Target | Result |")
        lines.append("|-------|--------|--------|")
        for p in report.probe_results:
            status = "✅ HELD" if p.passed else "❌ VULNERABLE"
            lines.append(f"| {p.probe_name} | `{p.target}` | {status} |")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Mini-MDASH Security Harness v1.0 — {report.timestamp}*")

    return "\n".join(lines)


def to_json(report: SecurityReport) -> str:
    """Generate a JSON security report for CI/CD integration."""
    data = {
        "version": "1.0",
        "timestamp": report.timestamp,
        "target": report.target,
        "total_files_scanned": report.total_files_scanned,
        "summary": report.summary,
        "findings": [
            {
                "rule_id": f.rule_id,
                "title": f.title,
                "severity": f.severity.value,
                "file": f.file,
                "line": f.line,
                "description": f.description,
                "evidence": f.evidence,
                "confidence": f.confidence,
                "remediation": f.remediation,
                "cwe": f.cwe,
                "scanner": f.scanner,
            }
            for f in report.findings
        ],
        "probe_results": [
            {
                "probe_name": p.probe_name,
                "target": p.target,
                "passed": p.passed,
                "details": p.details,
            }
            for p in report.probe_results
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False)


def to_telegram(report: SecurityReport) -> str:
    """Generate a concise Telegram notification for critical findings."""
    s = report.summary
    total = s.get("total_findings", 0)
    critical = s.get("critical", 0)
    high = s.get("high", 0)

    if critical > 0:
        verdict = "🔴 CRITICAL"
    elif high > 0:
        verdict = "🟠 HIGH RISK"
    else:
        verdict = "✅ CLEAN"

    msg = (
        f"🛡️ **Mini-MDASH Security Scan**\n"
        f"Target: `{_short_path(report.target)}`\n"
        f"Verdict: **{verdict}**\n"
        f"Findings: {total} (🔴{critical} 🟠{high} 🟡{s.get('medium', 0)})\n"
    )

    # List critical findings
    if critical > 0:
        msg += "\n**Critical Issues:**\n"
        for f in report.findings:
            if f.severity == Severity.CRITICAL:
                msg += f"• [{f.rule_id}] {f.title}\n"

    return msg


def _short_path(path: str) -> str:
    """Shorten path for display."""
    parts = path.replace("\\", "/").split("/")
    if len(parts) > 3:
        return "/".join(parts[-3:])
    return path
