"""
P6 — Morning Brief Generator
Orchestrates: Watchlist scan → Screenshot → RAG → Claude → Telegram
"""
import logging
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Optional
from zoneinfo import ZoneInfo

import config
from mcp_client import get_mcp_client
from watchlist import get_watchlist
from analysis import scan_symbols, ScanResult
from rag import query_knowledge, generate_trading_advice
from notifier import send_telegram_message, send_telegram_photo
from vision import analyze_chart_vision, format_vision_telegram
import database

logger = logging.getLogger(__name__)

ICT = ZoneInfo("Asia/Ho_Chi_Minh")

# Store latest brief in memory
_latest_brief: Optional[dict] = None


def _format_brief_text(
    scan_results: list[ScanResult],
    ai_analysis: str,
    timestamp: datetime,
) -> str:
    """Format morning brief as Telegram-friendly text."""
    now_str = timestamp.strftime("%d/%m/%Y %H:%M ICT")
    n = len(scan_results)

    lines = [
        f"🌅 *MORNING BRIEF — {now_str}*",
        f"📊 Watchlist scan: *{n} symbols*",
        "",
    ]

    # Per-symbol table inside code block for clean alignment
    lines.append("```")
    lines.append(f"{'Symbol':<12} │ {'Price':>10} │ {'TT':^4} │ {'Vol%':>5} │ {'VCP':<3}")
    lines.append("─" * 46)

    errors = []
    for r in scan_results:
        if r.error:
            lines.append(
                f"{r.symbol:<12} │ {0.0:>10.2f} │  ?/8 │ {'100%':>5} │ ❌"
            )
            errors.append(f"❌ *{r.symbol}*: {r.error}")
            continue

        vcp_flag = "⭐" if r.vcp.detected else ""
        vol_pct = f"{r.vcp.volume_ratio*100:.0f}%"
        price_str = f"{r.price:,.2f}" if r.price >= 1 else f"{r.price:.4f}"

        lines.append(
            f"{r.symbol:<12} │ {price_str:>10} │ {r.trend_template.score:>2}/8 │ {vol_pct:>5} │ {vcp_flag:<3}"
        )

    lines.append("```")
    lines.append("")

    if errors:
        for err in errors:
            lines.append(err)
        lines.append("")

    # VCP highlights
    vcps = [r for r in scan_results if r.vcp.detected and not r.error]
    if vcps:
        lines.append("🎯 *VCP Setups đáng chú ý:*")
        for r in vcps:
            lines.append(f"• *{r.symbol}*: {r.vcp.note}")
            if r.vcp.pivot_level:
                lines.append(f"  → Pivot breakout: `{r.vcp.pivot_level:,.2f}`")
        lines.append("")

    # AI analysis
    lines.append("🧠 *Minervini AI Assessment:*")
    lines.append(ai_analysis)
    lines.append("")
    lines.append("─" * 45)
    lines.append("_Generated by TradingViewProject v6.0_")

    return "\n".join(lines)


async def generate_morning_brief() -> Optional[dict]:
    """
    Full morning brief orchestration:
    1. Get watchlist
    2. MCP scan (quote + study values)
    3. Screenshot top VCP candidate
    4. RAG + Claude analysis
    5. Send Telegram (text + photo)
    6. Return brief dict
    """
    global _latest_brief
    mcp = get_mcp_client()
    timestamp = datetime.now(ICT)

    logger.info(f"[Brief] Starting morning brief at {timestamp.isoformat()}")

    # 1. Get watchlist
    symbols = get_watchlist()
    if not symbols:
        logger.warning("[Brief] Watchlist is empty — skipping brief")
        return None

    # 2. MCP health check
    health = await mcp.health_check()
    if not health.get("connected") and config.MCP_ENABLED:
        logger.warning("[Brief] TradingView MCP not connected — brief may have limited data")

    # 3. Scan symbols
    logger.info(f"[Brief] Scanning {len(symbols)} symbols: {symbols}")
    try:
        scan_results = await scan_symbols(symbols, mcp)
    except Exception as e:
        logger.error(f"[Brief] Scan failed: {e}")
        scan_results = []

    # 4. Screenshot top VCP (or top TT score)
    screenshot_path: Optional[Path] = None
    top_candidates = [r for r in scan_results if r.vcp.detected and not r.error]
    if not top_candidates:
        top_candidates = [r for r in scan_results if not r.error]

    if top_candidates and config.MCP_ENABLED and health.get("connected"):
        top = top_candidates[0]
        logger.info(f"[Brief] Capturing screenshot for {top.symbol}")
        try:
            import re
            safe_symbol = re.sub(r'[^A-Za-z0-9_\-]', '', top.symbol)
            screenshot_path = await mcp.capture_screenshot(
                symbol=top.symbol,
                timeframe="D",
                region="chart",
                save_path=Path(__file__).parent / "screenshots" / f"brief_{safe_symbol}_{timestamp.strftime('%Y%m%d')}.png"
            )
        except Exception as e:
            logger.warning(f"[Brief] Screenshot failed: {e}")

    # 4b. AI Vision analysis on screenshot (P7)
    vision_result = None
    # Check if ANY AI vision provider is available (Gemini or Anthropic)
    _has_vision = (
        (getattr(config, "AI_PROVIDER", "anthropic").lower() == "gemini" and
         (getattr(config, "GEMINI_API_KEY", None) or getattr(config, "GCP_PROJECT_ID", None)))
        or
        (getattr(config, "AI_PROVIDER", "anthropic").lower() == "anthropic" and
         getattr(config, "ANTHROPIC_API_KEY", None) and
         not getattr(config, "ANTHROPIC_API_KEY", "").startswith("sk-ant-xxx"))
    )
    if screenshot_path and screenshot_path.exists() and _has_vision:
        logger.info(f"[Brief] Running AI Vision analysis ({config.AI_PROVIDER}) on {screenshot_path.name}")
        try:
            # Prepare scan result dict for combined scoring
            top_scan_dict = None
            if top_candidates:
                top = top_candidates[0]
                top_scan_dict = {
                    "price": top.price,
                    "trend_template_score": top.trend_template.score,
                    "trend_template_stage": top.trend_template.stage,
                    "vcp_detected": top.vcp.detected,
                    "volume_ratio": top.vcp.volume_ratio,
                    "pivot_level": top.vcp.pivot_level,
                }

            vision_result = await analyze_chart_vision(
                image_path=screenshot_path,
                symbol=top_candidates[0].symbol if top_candidates else "UNKNOWN",
                scan_result=top_scan_dict,
            )
            if vision_result and not vision_result.get("error"):
                logger.info(f"[Brief] Vision: confidence={vision_result['confidence']}/10, "
                           f"patterns={vision_result['patterns']}")
            else:
                logger.warning(f"[Brief] Vision analysis error: {vision_result.get('error')}")
        except Exception as e:
            logger.warning(f"[Brief] Vision analysis failed: {e}")
    elif screenshot_path and not _has_vision:
        logger.warning("[Brief] Vision skipped — no AI provider configured (check GEMINI_API_KEY or ANTHROPIC_API_KEY)")

    # 5. RAG + AI analysis (Claude or Gemini fallback)
    ai_analysis = ""
    has_gemini = bool(config.GEMINI_API_KEY or config.GCP_PROJECT_ID)
    has_anthropic = bool(config.ANTHROPIC_API_KEY and not config.ANTHROPIC_API_KEY.startswith("sk-ant-xxx"))
    
    if config.RAG_ENABLED and (has_anthropic or has_gemini):
        try:
            # Build context from top results
            vcp_symbols = [r.symbol for r in scan_results if r.vcp.detected and not r.error]
            top_tt = sorted([r for r in scan_results if not r.error],
                           key=lambda x: x.trend_template.score, reverse=True)[:3]

            query = f"Morning brief scan: VCP setups {vcp_symbols}, " \
                    f"top Trend Template scores {[f'{r.symbol}:{r.trend_template.score}/8' for r in top_tt]}, " \
                    f"Stage 2 analysis market overview"

            chunks = query_knowledge(query, n_results=config.RAG_TOP_K)

            # Build signal dict for generate_trading_advice
            signal_data = {
                "type": "morning_brief",
                "symbols_scanned": len(symbols),
                "vcp_detected": vcp_symbols,
                "top_tt_scores": [f"{r.symbol}: {r.trend_template.score}/8" for r in top_tt],
                "timestamp": timestamp.isoformat(),
            }

            try:
                ai_analysis = await generate_trading_advice(
                    symbol="WATCHLIST",
                    action="brief",
                    price="N/A",
                    payload=signal_data,
                    rag_chunks=chunks,
                )
                if "⚠️" in ai_analysis and has_gemini and config.AI_PROVIDER != "gemini":
                    logger.warning("[Brief] Anthropic advice generation returned error. Trying Gemini fallback...")
                    original_provider = config.AI_PROVIDER
                    config.AI_PROVIDER = "gemini"
                    try:
                        ai_analysis = await generate_trading_advice(
                            symbol="WATCHLIST",
                            action="brief",
                            price="N/A",
                            payload=signal_data,
                            rag_chunks=chunks,
                        )
                    finally:
                        config.AI_PROVIDER = original_provider
            except Exception as e:
                if has_gemini and config.AI_PROVIDER != "gemini":
                    logger.warning(f"[Brief] Anthropic advice generation failed: {e}. Trying Gemini fallback...")
                    original_provider = config.AI_PROVIDER
                    config.AI_PROVIDER = "gemini"
                    try:
                        ai_analysis = await generate_trading_advice(
                            symbol="WATCHLIST",
                            action="brief",
                            price="N/A",
                            payload=signal_data,
                            rag_chunks=chunks,
                        )
                    finally:
                        config.AI_PROVIDER = original_provider
                else:
                    raise e
        except Exception as e:
            logger.warning(f"[Brief] AI analysis failed: {e}")
            ai_analysis = "_AI analysis unavailable_"
    else:
        ai_analysis = "_RAG/Claude/Gemini not configured — enable GEMINI_API_KEY or ANTHROPIC_API_KEY and RAG_ENABLED_"

    # 6. Format brief
    brief_text = _format_brief_text(scan_results, ai_analysis, timestamp)

    # 6b. Append Vision analysis if available
    if vision_result and not vision_result.get("error"):
        vision_text = format_vision_telegram(vision_result)
        brief_text += "\n\n" + vision_text

    # 7. Send Telegram
    try:
        if screenshot_path and screenshot_path.exists():
            await asyncio.to_thread(send_telegram_photo, screenshot_path, caption=brief_text[:1024])
            # Send full text if caption truncated
            if len(brief_text) > 1024:
                await asyncio.to_thread(send_telegram_message, brief_text)
        else:
            await asyncio.to_thread(send_telegram_message, brief_text)
        logger.info("[Brief] Morning brief sent to Telegram ✅")
    except Exception as e:
        logger.error(f"[Brief] Telegram send failed: {e}")

    # 8. Cache
    brief = {
        "timestamp": timestamp.isoformat(),
        "symbols_scanned": len(symbols),
        "scan_results": [
            {
                "symbol": r.symbol,
                "price": r.price,
                "change_pct": r.change_pct,
                "trend_template_score": r.trend_template.score,
                "trend_template_stage": r.trend_template.stage,
                "vcp_detected": r.vcp.detected,
                "volume_ratio": r.vcp.volume_ratio,
                "pivot_level": r.vcp.pivot_level,
                "note": r.vcp.note,
                "error": r.error,
            }
            for r in scan_results
        ],
        "ai_analysis": ai_analysis,
        "vision": vision_result if vision_result else None,
        "screenshot": str(screenshot_path) if screenshot_path else None,
        "text": brief_text,
        "success": True,
    }
    _latest_brief = brief

    # 9. Persist to SQLite
    try:
        import json as _json
        await database.insert_brief(
            symbols_scanned=len(symbols),
            scan_data=_json.dumps(brief["scan_results"]),
            ai_analysis=ai_analysis,
            vision_data=_json.dumps(vision_result) if vision_result else None,
            screenshot=str(screenshot_path) if screenshot_path else None,
            brief_text=brief_text,
            success=1,
        )
    except Exception as e:
        logger.warning(f"[Brief] Failed to persist brief to DB: {e}")

    return brief


def get_latest_brief() -> Optional[dict]:
    """Return the most recent morning brief."""
    return _latest_brief
